apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-example-app
spec:
  replicas: 2 # You can adjust the number of replicas
  selector:
    matchLabels:
      app: argocd-example-app
  template:
    metadata:
      labels:
        app: argocd-example-app
    spec:
      containers:
      - name: argocd-example-app
        image: liquidreply/argocd-example-app:1
        ports:
        - containerPort: 3000 # Assuming your app runs on port 3000
