apiVersion: v1
kind: Service
metadata:
  name: argocd-example-app-service
spec:
  type: NodePort
  selector:
    app: argocd-example-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000 # Optional: Kubernetes will choose a port if this is omitted
